import Head from 'next/head'
import Image from 'next/image'
import PageLayout from "../src/components/layout/PageLayout"
import p1Shoot from "../src/assets/images/P1/p1-9.jpg"
import Link from 'next/dist/client/link'

import styled from 'styled-components';

export default function Home() {
  return (
    
    <PageLayout>
      <Head>
        <title>Yatri Motorcycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledHome>
        <Image src={p1Shoot} alt="Project one" layout="fill" objectFit='cover'/>
        <h1>PROJECT <span>ONE</span></h1>
        <div className='cta-btn'>
          <Link href={"/project-one"}><a className='discover'>DISCOVER P1</a></Link>
          <Link href={"/project-one/pre-order"}><a className='reserve'>RESERVE NOW</a></Link>
        </div>
      </StyledHome>
     
      </PageLayout>
  )
}

const StyledHome = styled.div`

  margin-top:-10rem ;

  position: relative;
   width:100% ;
   height: 100vh ;
   overflow: hidden;

   h1{
     position: absolute;
     z-index: 1000;

     top: 20%;
     left: 50%;
     transform: translateX(-50%) ;

     color: #fff;

     font-size: 3.5rem;
     font-weight: 600 ;
     letter-spacing: 0.51rem ;
   }

   span{
     color: #0cc;
   }

   .cta-btn{
     display: flex;
     gap: 2rem;

     position: absolute;
     z-index: 1000;

     bottom: 10%;
     left: 50%;
     transform: translateX(-50%) ;

     .discover,.reserve{
       display:inline-block ;

       border: 0.2px solid #fff;

       padding: 1rem 2rem;

       font-size: 1.3rem;
       font-weight: 600 ;
       letter-spacing: 0.34rem ;
       color: #fff;
       transition:all 0.2s ease ;

       &:hover{
         transform:scale(1.1) ;
       }
     }
     .reserve{
       background-color:#0cc ;
       border-color: #0cc;

     }
   }

`